version: '3'

services:
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlDB
    restart: always
    environment:
      MYSQL_DATABASE: ptonKawa
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  apiwebshop:
    container_name: apiwebshop
    build: ./APIWebshop
    restart: always
    ports:
      - "3000:3000"
    environment:
      - ACCESS_TOKEN_SECRET=4242XX424208
      - REFRESH_TOKEN_SECRET=424200000X1
      - SALT=coucou
      - IDENTIFIANT=admin
      - PASSWORD=jVKXQklv71GxSVYp

  apireseller:
    container_name: apireseller
    build: ./APIReseller
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      - ACCESS_TOKEN_SECRET=4242XX424208
      - REFRESH_TOKEN_SECRET=424200000X1
      - IDENTIFIANT=admin
      - PASSWORD=jVKXQklv71GxSVYp
  
  dolibarr:
    container_name: dolibarr
    build: ./
    restart: always
    ports:
      - "8082:80"
