version: '3'

services:
  apiwebshop:
    container_name: apiwebshop
    build: ./apiwebshop
    ports:
      - "3000:3000"
    environment:
      - ACCESS_TOKEN_SECRET=4242XX424208
      - REFRESH_TOKEN_SECRET=424200000X1
      - IDENTIFIANT=admin
      - PASSWORD=jVKXQklv71GxSVYp

  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9000:9000"

  # jenkins

  apireseller:
    container_name: apireseller
    build: ./apireseller
    ports:
      - "3001:3000"
    environment:
      - ACCESS_TOKEN_SECRET=4242XX424208
      - REFRESH_TOKEN_SECRET=424200000X1
      - IDENTIFIANT=admin
      - PASSWORD=jVKXQklv71GxSVYp