version: '3'

services:
  jenkins: 
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    user: root
    restart: always
    volumes:
        - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
        - ./var/run/docker.sock:/var/run/docker.sock
        # - ./usr:/usr/local/bin/docker