version: '3'

services:
  jenkins: 
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    user: root
    restart: always
    volumes:
        - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        # - ./usr:/usr/local/bin/docker

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: